export const homeObjOne = {
  lightBg: false,
  primary: true,
  imgStart: "",
  lightTopLine: true,
  lightTextDesc: true,
  buttonLabel: "See Projects",
  description: "Full Stack Engineer",
  headline: "Welcome to my Personal Portfolio",
  lightText: true,
  topLine: "Cameron McCloskey",
  img: require("../../images/svg3.svg").default,
  alt: "Image",
  start: "",
};

export const homeObjThree = {
  lightBg: false,
  primary: true,
  imgStart: "",
  lightTopLine: true,
  lightTextDesc: true,
  buttonLabel: "See Projects",
  description: "Full Stack Engineer",
  headline: "Welcome to my Personal Portfolio",
  lightText: true,
  topLine: "Cameron McCloskey",
  img: require("../../images/svg1.svg").default,
  alt: "Image",
  start: "",
};

export const homeObjFour = {
  lightBg: false,
  primary: true,
  imgStart: "",
  lightTopLine: true,
  lightTextDesc: true,
  buttonLabel: "See Projects",
  description: "Full Stack Engineer",
  headline: "Welcome to my Personal Portfolio",
  lightText: true,
  topLine: "Cameron McCloskey",
  img: require("../../images/svg4.svg").default,
  alt: "Image",
  start: "",
};
