export const homeObjOne = {
  id: "home",
  lightBg: false,
  primary: true,
  imgStart: "",
  lightTopLine: true,
  lightTextDesc: true,
  buttonLabel: "See Projects",
  description: "Full Stack Engineer",
  headline: "Welcome to my Personal Portfolio",
  lightText: true,
  topLine: "Cameron McCloskey",
  img: require("../../images/svg3.svg").default,
  alt: "Image",
  start: "",
};

export const ObjTwo = {
  id: "about",
  lightBg: true,
  primary: false,
  imgStart: "start",
  lightTopLine: false,
  lightTextDesc: false,
  buttonLabel: "Technologies I use",
  description:
    "Hi there. My name is Cameron and I'm a Full Stack Developer. I'm from California and I've been writing software for 2 years. I specialize in React utilizing the MERN stack, but have also used Python and Java. Feel free to check out some of my work below.",
  headline: "",
  lightText: false,
  topLine: "About",
  img: require("../../images/svg2.svg").default,
  alt: "Image",
  start: "true",
};

export const homeObjThree = {
  id: "technologies",
  lightBg: false,
  primary: true,
  imgStart: "",
  lightTopLine: true,
  lightTextDesc: true,
  buttonLabel: "See Projects",
  description: "",
  headline: "",
  lightText: true,
  topLine: "Technologies",
  img: require("../../images/svg1.svg").default,
  alt: "Image",
  start: "",
};

export const homeObjFour = {
  lightBg: false,
  primary: true,
  imgStart: "",
  lightTopLine: true,
  lightTextDesc: true,
  buttonLabel: "Contact",
  description: "Full Stack Engineer",
  headline: "Ipsum lorem.",
  lightText: true,
  topLine: "",
  img: require("../../images/svg4.svg").default,
  alt: "Image",
  start: "",
};
